Use built-in expand() without fern.vim only for the first hijack
lambdalisue/fern-hijack.vim pull request #13
Opened 2023-09-02 10:48 UTC by gw31415

Thank you for the wonderful plugin.

The current implementation uses `fern#util#expand` in `s:expand` even on the first `BufEnter`.
This causes it to load even on the first startup even if it is not necessary to load `fern.vim`, for example when opening a file (not a directory).

In this PR, only the first time `BufEnter` does not try `fern#util#expand`, but uses `expand()`.
This enables for lazy loading of `fern.vim`, which should improve startup speed.

Thanks.

2023-09-07 04:58 UTC, lambdalisue requested changes
I see. Well, then let's check the presence of `fern#util#expand` itself instead and describe the reason as a function comment (outside of the function) like

```vim
" explain why we check the presence of `fern#util#expand` which usually shoud not
function! s:expand(expr) abort
  if exists('fern#util#expand')
    return fern#util#expand(a:expr)
  endif
  return expand(a:expr)
endfunction
```

2023-09-07 06:01 UTC, gw31415 commented
Thanks for the advice on better changes. I've made the changes.

2023-09-11 14:50 UTC, lambdalisue approved these changes

2023-09-11 14:50 UTC, merged

2023-09-12 09:30 UTC, gw31415 commented
Thanks!